import { defineConfig } from "orval";

export default defineConfig({
  mysweldo: {
    input: {
      target: "./src/docs/openapi/specs.json",
    },
    output: {
      target: "./src/api/generated/endpoints",
      schemas: "./src/api/generated/model",
      client: "react-query",
      mode: "tags-split",
      clean: true,
      override: {
        mutator: {
          path: "./src/api/mutator.ts",
          name: "customInstance",
        },
        query: {
          useInfinite: false,
        },
        header: (info) =>
          `/**
 * Generated by orval — do not edit manually.
 * ${info.title} ${info.version}
 */`,
      },
    },
  },
});